---
- name: httpd on x64_redhat_linux_6-yum
  become_user: '{{ INSTALL_USER }}'
  hosts: httpproxy:&sas-hosts-x64_redhat_linux_6-yum
  pre_tasks:
  - name: include soe.yml
    include_vars: '{{ item }}'
    with_first_found:
    - '{{ orchestration_root }}/soe.yml'
    - '{{ orchestration_root }}/internal/soe_defaults.yml'
  roles:
  - httpd-x64_redhat_linux_6-yum
  vars_files:
  - ../vars.yml

