- name: Include redhat repo-setup role
  include_role:
    name: repo-setup-x64_redhat_linux_6-yum
  when: inventory_hostname in groups['sas-hosts-x64_redhat_linux_6-yum'] | default([])
  static: no

- name: Include suse repo-setup role
  include_role:
    name: repo-setup-x64_suse_linux_12-yum
  when: inventory_hostname in groups['sas-hosts-x64_suse_linux_12-yum'] | default([])
  static: no
