---
# file: site.yml
- hosts: sas-all
  tasks:
  - set_fact:
      orchestration_root: "{{ playbook_dir }}"

- include: internal/deploy-preinstall.yml
- include: internal/deploy-install.yml
- include: internal/deploy-configure.yml
- include: internal/deploy-complete.yml