---
apiVersion: v1
kind: Service
metadata:
  name: sas-viya-httpproxy

spec:
  selector:
    app: sas-viya-httpproxy
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 80
    - name: "443"
      protocol: TCP
      port: 443
      targetPort: 443
  sessionAffinity: None
  clusterIP: None
