---
apiVersion: v1
kind: Service
metadata:
  name: sas-viya-programming

spec:
  selector:
    app: sas-viya-programming
  ports:
    - name: "7080"
      protocol: TCP
      port: 7080
      targetPort: 7080
  sessionAffinity: None
  clusterIP: None
