---
- name:  Run the SAS/ACCESS Interface to Hadoop (SPRE) program to validate that the required Hadoop client files exist
  hosts: programming
  gather_facts: yes

  vars_files:
    - ../vars.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ playbook_dir }}/../soe.yml"
      - "{{ playbook_dir }}/../internal/soe_defaults.yml"

  roles:
    - hadooptracer-runvalidation

