---
- include: "{{ playbook_dir }}/../internal/gather-host-facts.yml"

- name: Rebuild SAS trust stores
  hosts: sas-all
  tasks:
  - include: "{{ playbook_dir }}/../tasks/rebuild-trust-stores.yml"
    vars:
      COMBINED_GROUP: '{{ groups[''consul''] }}'
  vars_files:
  - ../vars.yml
